// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MoveImagesInput struct {
	AlbumID      string   `json:"albumId"`
	SrcDirIndex  int      `json:"srcDirIndex"`
	DestDirIndex int      `json:"destDirIndex"`
	FileNames    []string `json:"fileNames"`
}

type MoveImagesResult struct {
	Succeeded []string `json:"succeeded"`
	Failed    []string `json:"failed"`
}

type TrashImagesInput struct {
	AlbumID     string   `json:"albumId"`
	SrcDirIndex int      `json:"srcDirIndex"`
	FileNames   []string `json:"fileNames"`
}
